spring:
  application:
    name: course-material
  datasource:
    url: jdbc:mysql://localhost:3306/coursematerial
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 9096
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
spring.cloud.config:
  uri: http://localhost:8888
logging:
  level:
    org.springframework.cloud.config: DEBUG
spring.cloud.config.override-none: true
spring.cloud.config.enabled: false
course:
  service:
    url=http://localhost:8080:

# swagger-ui custom path
springdoc:
  swagger-ui:
  path: /swagger-ui.html
